use_frameworks!

platform :ios, '8.0'

target 'TFPhotoPicker_Example' do
  pod 'TFPhotoPicker', :path => '../'

  target 'TFPhotoPicker_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
